name: QLOP CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Specify your project's Python version

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
      
      - name: Run Black (check formatting)
        run: black --check . --exclude "(venv|.venv|migrations)"

      - name: Run Flake8 (linting)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv,.venv,migrations,__pycache__

  test:
    name: Run Tests and Coverage
    runs-on: ubuntu-latest
    needs: lint # Optional: Run tests only if linting passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install project dependencies and dev dependencies (which should include pytest, pytest-cov)
          pip install -r requirements.txt 
          pip install -e .[dev] 
          # Explicitly install pytest and pytest-cov if not fully covered by [dev] or for clarity
          pip install pytest pytest-cov 

      - name: Run tests with Pytest and generate coverage report
        run: pytest tests/ --cov=src --cov-report=xml --cov-report=term-missing

      - name: Upload coverage reports to Github Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml # Path to the coverage report file

  docker-build:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    needs: test # Optional: Run Docker build only if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t qlop-ci-test:latest .

      - name: Run a simple test on the Docker container
        run: docker run --rm qlop-ci-test:latest python main.py --help
        # This ensures the container starts and the main CLI entrypoint is accessible.

      # Optional: More comprehensive tests using docker-compose.test.yml
      # - name: Run tests using docker-compose
      #   run: |
      #     docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
      #   # This assumes docker-compose.test.yml is configured to run tests and exit appropriately.

# Future potential jobs:
# - deploy-docs: Build and deploy documentation (e.g., to GitHub Pages)
# - publish-package: Build and publish Python package to PyPI (on new tags/releases)
# - deploy-docker-image: Push Docker image to a registry (e.g., Docker Hub, GHCR) on new releases
```
